---
name: Deploy

'on':
  create:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-py39-django32-${{ hashFiles('setup.py', 'tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-py39-django32-

      - name: Install dependencies
        run: pip install build==0.8.*

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
